import { ENV_MODE, GA4_MEASUREMENT_ID_ENV, GTM_ID_ENV, IS_PROD } from '../config/env'

const GTM_PLACEHOLDER = 'GTM-XXXXXXX'
const GA4_PLACEHOLDER = 'G-XXXXXXXXXX'

export const GTM_ID = GTM_ID_ENV ?? GTM_PLACEHOLDER
export const GA4_MEASUREMENT_ID = GA4_MEASUREMENT_ID_ENV ?? GA4_PLACEHOLDER
export const ANALYTICS_ENV = ENV_MODE

export const IS_GTM_CONFIGURED =
  typeof GTM_ID === 'string' && GTM_ID.length > 0 && GTM_ID !== GTM_PLACEHOLDER

export const IS_GA4_CONFIGURED =
  typeof GA4_MEASUREMENT_ID === 'string' &&
  GA4_MEASUREMENT_ID.length > 0 &&
  GA4_MEASUREMENT_ID !== GA4_PLACEHOLDER

export const IS_ANALYTICS_ENABLED = IS_PROD && IS_GTM_CONFIGURED
